name: Build Executables

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022] # ubuntu-22.04, ubuntu-22.04-arm, macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libasound2-dev

#      - name: Install dependencies (macOS)
#        if: startsWith(matrix.os, 'macos')
#        run: brew install --cask cmake

      - name: Install dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: build/Synth_*
