name: Build Executables

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, ubuntu-22.04-arm, macos-13]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libasound2-dev

#      - name: Install dependencies (macOS)
#        if: startsWith(matrix.os, 'macos')
#        run: brew install --cask cmake

      - name: Install dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build
        env:
          CMAKE_BUILD_TYPE: Release
          
      - name: Build Python wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.16.5
        with:
          package-dir: python
        env:
          CIBW_BUILD: cp3*-* # build for all CPython versions

      - name: Build C++ project
        run: |
             cmake --build build --config Release

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Synth_Dexed-${{ matrix.os }}
          path: |
                build/Release/Synth_*
                build/Synth_*
                Synth_*
                python/wheelhouse/*.whl
                python/main_python.py
                python/test_dexed.py
