name: Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
       
      - uses: izer-xyz/openwrt-imagebuilder-action@main
        with:
          image: bcm27xx-bcm2710
          profile: rpi-3
          openwrt-version: 24.10.1
          packages: >-
            -firewall4 -ca-bundle -dnsmasq -dropbear   
            -kmod-nft-offload -libustream-wolfssl -logd  
            -nftables -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe -uclient-fetch 
          files: test/files
          rootfs-size: 10
          #debug: 1
          #disabled-services: dhcp
         # extra-image-name: useless

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          path: bin/*
          retention-time: 1d
