name: Firmware

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrt/imagebuilder:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build firmware image
        run: |
          mkdir -p files/
          make image \
          PROFILE="rpi-3" \
          PACKAGES="nano" \
          FILES="files" \
          DISABLED_SERVICES="dnsmasq firewall odhcpd"

      - name: Upload built images
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-images
          path: bin/targets/bcm27xx/bcm2710/openwrt-*-rpi-3-squashfs-factory.img.gz
