name: Sync from Codeberg

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * 4'

jobs:
  mirror:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [master, dev]

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config user.name "GitHub Action"
        git config user.email "actions@github.com"

    - name: Add Codeberg remote and fetch
      run: |
        git remote add upstream https://codeberg.org/dcoredump/Synth_Dexed.git || true
        git fetch upstream

    - name: Sync ${{ matrix.branch }} branch
      run: |
        # Check out or create the branch locally
        git checkout -B ${{ matrix.branch }}

        # Hard reset to upstream branch (mirror)
        git reset --hard upstream/${{ matrix.branch }}

    - name: Force push ${{ matrix.branch }} to GitHub
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: ${{ matrix.branch }}
