name: Teensy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [teensy36, teensy40, teensy41]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build all examples for ${{ matrix.board }}
        run: |
          for example in examples/*/*.ino; do
            example_dir=$(dirname "$example")
            echo "Building $example for ${{ matrix.board }}"
            pio ci "$example" --board=${{ matrix.board }} --lib="${example_dir}/" --lib="src/"
          done
